kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config-map
  namespace: mysql
data:
  MYSQL_DATABASE: devops
ubuntu@ip-10-0-1-200:~/kubernetes/mysql$ ^C
ubuntu@ip-10-0-1-200:~/kubernetes/mysql$ cat secrets.yml
kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo=  # value is base64 encoded
